name:                mimizu
version:             0.1.0.0
license:             MIT
author:              Apple Princess
maintainer:          Apple Princess
copyright:           2018 Apple Princess
category:            Web
github:              appleprincess/Mimizu-Controller
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - time

library:
  source-dirs: src

  
