name:                mimizu
version:             0.1.0.0
license:             MIT
author:              Apple Princess
maintainer:          Apple Princess
copyright:           2018 Apple Princess
category:            Web
github:              appleprincess/Mimizu-Controller
extra-source-files:
- README.md

dependencies:
  - array
  - base >= 4.7 && < 5
  - bytestring
  - network
  - time
  - text
  - websockets

library:
  source-dirs: src

executables:
  mimizu:
    main: Main.hs
    source-dirs: app/SampleBot
    dependencies:
      - containers
      - mimizu

  chat:
    main: Main.hs
    source-dirs: app/CommentReader
    dependencies:
      - directory
      - haskeline
      - mimizu
      - optparse-applicative
      - process

